const express=require('express')
const router=express.Router()
const{validateRequest,validatesigninRequest,isValidatedRequest}=require('../validate/validate')
const {verifyOtp}=require('../Controller/VerfifyOtp')
const {signup}=require('../Controller/Signup')
const {resendOtp}=require('../Controller/ResendOtP')
const {Signin}=require('../Controller/Signin')
const{otpsend}=require('../Controller/ForgotPassword/sendOtP')
const{newPass}=require('../Controller/ForgotPassword/newPass')
router.post('/Signup',validateRequest,isValidatedRequest,signup)
router.post('/Signin',validatesigninRequest,isValidatedRequest,Signin)
router.post('/Verifyotp',verifyOtp)
router.post('/resendOtp',resendOtp)
router.post('/forgotpass/sendotp',otpsend)
router.post('/forgotpass/create_new',newPass)
module.exports=router

